version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "covidUpdater"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cn5614xlwj3b"
s3_prefix = "covidUpdater"
region = "us-east-1"
profile = "archdev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

